name: lighthouse-ci
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: yarn, build
        run: |
          npm install -g yarn
          yarn
          yarn build
      - name: run Lighthouse CI
        run: |
          yarn dlx -p @lhci/cli@0.8.x lhci autorun
        env:
          LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
